FROM horovod/horovod:latest

RUN apt-get update && apt-get install -y libaio-dev llvm-10-dev

RUN /usr/bin/python -m pip install --upgrade pip

RUN DS_BUILD_CPU_ADAM=1 DS_BUILD_AIO=1 DS_BUILD_UTILS=1 pip install deepspeed \
    --global-option="build_ext" \
    --global-option="-j1" \
    --no-cache -v \
    --disable-pip-version-check

RUN pip install pytorch-lightning==1.3.8 transformers

